server:
  port: 8085
  cors:
    allowed-origins: "*"
    allowed-methods: "GET, POST, PUT, DELETE"
    allowed-headers: "*"
    allow-credentials: false
    max-age: 3600

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/foodMenu_db
    username: root
    password: Ardra@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update